spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.mcp.client.streamable-http.connections.customer.url=${CUSTOMER_SERVICE_URL:http://localhost:8056}/mcp
spring.ai.mcp.client.streamable-http.connections.ebank.url=${EBANK_SERVICE_URL:http://localhost:8057}/mcp
telegram.token=VOTRE_TOKEN_TELEGRAM_BOT
