spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.mcp.client.streamable-http.connections.customer.url=http://localhost:8056/mcp
spring.ai.mcp.client.streamable-http.connections.ebank.url=http://localhost:8057/mcp