customer.params.a=31
customer.params.b=41
spring.datasource.url=jdbc:postgresql://localhost:5433/customerdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update